---
title: "Berlin Impft!"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Generate dataset with coordinates for vaccination stations

```{r, eval=F, echo=T}

library(dplyr)

# Vector of vaccination center names
locations <- c("Velodrom", "Arena Berlin", "Flughafen Berlin-Tempelhof",
               "Erika-Heß-Eisstadion", "Flughafen Berlin-Tegel", 
               "Messe Berlin")

# Generate coordinates for locations + create dataframe
locations_geocoded <- geocode_OSM(locations)
locations_df <- select(locations_geocoded, query, lat, lon)

saveRDS(locations_df, file = "files/locations_df.rds")

```

#### Generate Leaflet map

```{r, echo=T, message=F, warning=F, fig.align='center'}

library(dplyr)
library(sf)
library(leaflet)

# Read in Berlin + Bezirke boundaries
berlin_st <- st_read("data/bezirksgrenzen.geojson")

locations_df <- readRDS(file = "data/locations_df.rds")

# Convert dataframe to simple features file (for ease of use w/ Mapview)
locations_sf <- st_as_sf(locations_df, coords = c("lon","lat"), crs = 4326)

### Generating maps 

locations_sp <- as(locations_sf, Class = "Spatial")

berlin_leaflet <- leaflet(data = locations_sp) %>%
  addTiles() %>%
  addPolygons(data = berlin_st, stroke = T, weight = .8) %>%
  addCircleMarkers(label = locations_sp$query, color = "red", stroke = F, fillOpacity = .5)
  
berlin_leaflet


```

<<<<<<< Updated upstream
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Include a map
```{r map}
library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map

```
=======
>>>>>>> Stashed changes
